export const employees = [
  {
    id: 1,
    name: "John",
    positionName: "CEO",
    phone: "99887766",
    email: "employee@email.com",
    location: "LA Branch",
    department: "",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    imageUrl: "https://randomuser.me/api/portraits/men/1.jpg",
  },
  {
    id: 2,
    name: "Smith",
    positionName: "COO",
    phone: "99887766",
    email: "employee@email.com",

    location: "LA Branch",
    department: "",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    imageUrl: "https://randomuser.me/api/portraits/men/20.jpg",
  },

  {
    id: 3,
    name: "Kate",
    positionName: "CTO",
    phone: "99887766",
    email: "employee@email.com",

    location: "LA Branch",
    department: "",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    imageUrl: "https://randomuser.me/api/portraits/women/3.jpg",
  },
  {
    id: 5,
    name: "Erica",
    positionName: "Manager of something",
    phone: "99887766",
    email: "employee@email.com",

    location: "LA Branch",
    department: "Marketing",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    imageUrl: "https://randomuser.me/api/portraits/women/8.jpg",
  },
  {
    id: 6,
    name: "Paul",
    positionName: "Manager of something",
    phone: "99887766",
    email: "employee@email.com",

    location: "LA Branch",
    department: "Marketing",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    imageUrl: "https://randomuser.me/api/portraits/men/6.jpg",
  },
  {
    id: 8,
    name: "Tony",
    positionName: "Manager of something",
    phone: "99887766",
    email: "employee@email.com",

    location: "LA Branch",
    department: "Marketing",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    imageUrl: "https://randomuser.me/api/portraits/men/8.jpg",
  },
  {
    id: 9,
    name: "Sally",
    positionName: "Manager of something",
    phone: "99887766",
    email: "employee@email.com",

    location: "LA Branch",
    department: "Marketing",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    imageUrl: "https://randomuser.me/api/portraits/women/9.jpg",
  },
  {
    id: 10,
    name: "Scott",
    positionName: "HR assistant",
    phone: "99887766",
    email: "employee@email.com",

    location: "LA Branch",
    department: "Marketing",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    imageUrl: "https://randomuser.me/api/portraits/men/10.jpg",
  },

  {
    id: 11,
    name: "James",
    positionName: "CGO",
    phone: "99887766",
    email: "employee@email.com",

    location: "LA Branch",
    department: "",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    imageUrl: "https://randomuser.me/api/portraits/men/7.jpg",
  },
  {
    id: 12,
    name: "Tony",
    positionName: "HR assistant",
    phone: "99887766",
    email: "employee@email.com",
    location: "LA Branch",
    department: "Marketing",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    imageUrl: "https://randomuser.me/api/portraits/men/8.jpg",
  },
  {
    id: 13,
    name: "Sally",
    positionName: "HR assistant",
    phone: "99887766",
    email: "employee@email.com",
    location: "LA Branch",
    department: "Marketing",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    imageUrl: "https://randomuser.me/api/portraits/women/9.jpg",
  },
  {
    id: 14,
    name: "Scott",
    positionName: "Teacher",
    phone: "99887766",
    email: "employee@email.com",
    location: "LA Branch",
    department: "Marketing",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    imageUrl: "https://randomuser.me/api/portraits/men/10.jpg",
  },

  {
    id: 15,
    name: "James",
    positionName: "Teacher",
    phone: "99887766",
    email: "employee@email.com",
    location: "LA Branch",
    department: "Marketing",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    imageUrl: "https://randomuser.me/api/portraits/men/7.jpg",
  },
  {
    id: 16,
    name: "Tony",
    positionName: "Developer",
    phone: "99887766",
    email: "employee@email.com",
    location: "LA Branch",
    department: "Marketing",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    imageUrl: "https://randomuser.me/api/portraits/men/8.jpg",
  },
  {
    id: 17,
    name: "Sally",
    positionName: "Developer",
    phone: "99887766",
    email: "employee@email.com",
    location: "LA Branch",
    department: "Marketing",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    imageUrl: "https://randomuser.me/api/portraits/women/9.jpg",
  },
  {
    id: 18,
    name: "Scott",
    positionName: "Teacher",
    phone: "99887766",
    email: "employee@email.com",
    location: "LA Branch",
    department: "Marketing",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    imageUrl: "https://randomuser.me/api/portraits/men/10.jpg",
  },
  {
    id: 19,
    name: "Tony",
    positionName: "Developer",
    phone: "99887766",
    email: "employee@email.com",
    location: "LA Branch",
    department: "Marketing",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    imageUrl: "https://randomuser.me/api/portraits/men/8.jpg",
  },
  {
    id: 20,
    name: "Tony",
    positionName: "Developer",
    phone: "99887766",
    email: "employee@email.com",
    location: "LA Branch",
    department: "Marketing",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    imageUrl: "https://randomuser.me/api/portraits/men/8.jpg",
  },
  {
    id: 21,
    name: "Tony",
    positionName: "Developer",
    phone: "99887766",
    email: "employee@email.com",
    location: "LA Branch",
    department: "Marketing",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    imageUrl: "https://randomuser.me/api/portraits/men/8.jpg",
  },
  {
    id: 22,
    name: "Tony",
    positionName: "Developer",
    phone: "99887766",
    email: "employee@email.com",
    location: "LA Branch",
    department: "Marketing",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    imageUrl: "https://randomuser.me/api/portraits/men/8.jpg",
  },
  {
    id: 23,
    name: "Tony",
    positionName: "Developer",
    phone: "99887766",
    email: "employee@email.com",
    location: "LA Branch",
    department: "Marketing",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    imageUrl: "https://randomuser.me/api/portraits/men/8.jpg",
  },
  {
    id: 24,
    name: "Tony",
    positionName: "Developer",
    phone: "99887766",
    email: "employee@email.com",
    location: "LA Branch",
    department: "Marketing",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    imageUrl: "https://randomuser.me/api/portraits/men/8.jpg",
  },
  {
    id: 25,
    name: "Tony",
    positionName: "Developer",
    phone: "99887766",
    email: "employee@email.com",
    location: "LA Branch",
    department: "Marketing",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    imageUrl: "https://randomuser.me/api/portraits/men/8.jpg",
  },
  {
    id: 26,
    name: "Tony",
    positionName: "Developer",
    phone: "99887766",
    email: "employee@email.com",
    location: "LA Branch",
    department: "Marketing",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    imageUrl: "https://randomuser.me/api/portraits/men/8.jpg",
  },
  {
    id: 27,
    name: "Tony",
    positionName: "Developer",
    phone: "99887766",
    email: "employee@email.com",
    location: "LA Branch",
    department: "Marketing",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    imageUrl: "https://randomuser.me/api/portraits/men/8.jpg",
  },
];

export const seats = [
  { posX: 2, posY: 13 },
  { posX: 3, posY: 13 },
  { posX: 4, posY: 13 },
  { posX: 5, posY: 13 },
  { posX: 6, posY: 13 },
  { posX: 7, posY: 13 },
  { posX: 7, posY: 11 },
  { posX: 6, posY: 11 },
  { posX: 5, posY: 11 },
  { posX: 4, posY: 11 },
  { posX: 3, posY: 11 },
  { posX: 2, posY: 11 },
  { posX: 2, posY: 10 },
  { posX: 3, posY: 10 },
  { posX: 4, posY: 10 },
  { posX: 5, posY: 10 },
  { posX: 6, posY: 10 },
  { posX: 7, posY: 10 },
  { posX: 7, posY: 8 },
  { posX: 6, posY: 8 },
  { posX: 5, posY: 8 },
  { posX: 4, posY: 8 },
  { posX: 3, posY: 8 },
  { posX: 2, posY: 8 },
  { posX: 5, posY: 5 },
  { posX: 4, posY: 5 },
  { posX: 3, posY: 5 },
  { posX: 2, posY: 5 },
  { posX: 2, posY: 6 },
  { posX: 3, posY: 6 },
  { posX: 4, posY: 6 },
  { posX: 5, posY: 6 },
  { posX: 3, posY: 1 },
  { posX: 4, posY: 1 },
  { posX: 5, posY: 1 },
  { posX: 6, posY: 1 },
  { posX: 3, posY: 3 },
  { posX: 4, posY: 3 },
  { posX: 5, posY: 3 },
  { posX: 6, posY: 3 },
  { posX: 9, posY: 1 },
  { posX: 9, posY: 3 },
  { posX: 11, posY: 1 },
  { posX: 11, posY: 3 },
  { posX: 12, posY: 1 },
  { posX: 12, posY: 2 },
  { posX: 12, posY: 3 },
  { posX: 12, posY: 4 },
  { posX: 14, posY: 1 },
  { posX: 14, posY: 2 },
  { posX: 14, posY: 3 },
  { posX: 14, posY: 4 },
  { posX: 15, posY: 1 },
  { posX: 15, posY: 2 },
  { posX: 15, posY: 3 },
  { posX: 15, posY: 4 },
  { posX: 17, posY: 4 },
  { posX: 17, posY: 3 },
  { posX: 17, posY: 2 },
  { posX: 17, posY: 1 },
];
