const employees = [
  {
    id: 1,
    parentId: "",
    givenName: "John",
    positionName: "CEO",
    phone: "99887766",
    email: "employee@email.com",
    team: "",
    location: "LA Branch",
    department: "",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    imageUrl: "https://randomuser.me/api/portraits/men/1.jpg",
  },
  {
    id: 2,
    parentId: "1",
    givenName: "Sam",
    positionName: "COO",
    phone: "99887766",
    email: "employee@email.com",
    team: "",
    location: "LA Branch",
    department: "",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    imageUrl: "https://randomuser.me/api/portraits/men/1.jpg",
  },
  {
    id: 3,
    parentId: "1",
    givenName: "Kate",
    positionName: "CTO",
    phone: "99887766",
    email: "employee@email.com",
    team: "",
    location: "LA Branch",
    department: "",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    imageUrl: "https://randomuser.me/api/portraits/men/1.jpg",
  },
  {
    id: 5,
    parentId: "1",
    givenName: "Erica Sara",
    positionName: "CFO",
    phone: "99887766",
    email: "employee@email.com",
    team: "",
    location: "LA Branch",
    department: "",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    imageUrl: "https://randomuser.me/api/portraits/men/1.jpg",
  },
  {
    id: 6,
    parentId: "1",
    givenName: "Paul",
    positionName: "CGO",
    phone: "99887766",
    email: "employee@email.com",
    team: "",
    location: "LA Branch",
    department: "",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    imageUrl: "https://randomuser.me/api/portraits/men/6.jpg",
  },
  {
    id: 17,
    parentId: "1",
    givenName: "Paul",
    positionName: "SUO",
    phone: "99887766",
    email: "employee@email.com",
    team: "",
    location: "LA Branch",
    department: "Marketing",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    imageUrl: "https://randomuser.me/api/portraits/men/6.jpg",
  },

  {
    id: 9,
    parentId: "2",
    givenName: "Sally",
    positionName: "Manager of something",
    phone: "99887766",
    email: "employee@email.com",
    team: "",
    location: "LA Branch",
    department: "Marketing",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    imageUrl: "https://randomuser.me/api/portraits/women/9.jpg",
  },
  {
    id: 10,
    parentId: "2",
    givenName: "Sally2",
    positionName: "Manager of something",
    phone: "99887766",
    email: "employee@email.com",
    team: "",
    location: "LA Branch",
    department: "Marketing",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    imageUrl: "https://randomuser.me/api/portraits/women/9.jpg",
  },
  {
    id: 11,
    parentId: "2",
    givenName: "Sally2",
    positionName: "Manager of something",
    phone: "99887766",
    email: "employee@email.com",
    team: "",
    location: "LA Branch",
    department: "Marketing",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    imageUrl: "https://randomuser.me/api/portraits/women/9.jpg",
  },
  {
    id: 12,
    parentId: "2",
    givenName: "Sally3",
    positionName: "Manager of something",
    phone: "99887766",
    email: "employee@email.com",
    team: "",
    location: "LA Branch",
    department: "Marketing",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    imageUrl: "https://randomuser.me/api/portraits/women/9.jpg",
  },
  {
    id: 13,
    parentId: "2",
    givenName: "Sally4",
    positionName: "Manager of something",
    phone: "99887766",
    email: "employee@email.com",
    team: "",
    location: "LA Branch",
    department: "Marketing",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    imageUrl: "https://randomuser.me/api/portraits/women/9.jpg",
  },
  {
    id: 14,
    parentId: "2",
    givenName: "Sally5",
    positionName: "Manager of something",
    phone: "99887766",
    email: "employee@email.com",
    team: "",
    location: "LA Branch",
    department: "Marketing",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    imageUrl: "https://randomuser.me/api/portraits/women/9.jpg",
  },
  {
    id: 15,
    parentId: "5",
    givenName: "Scott",
    positionName: "HR assistant",
    phone: "99887766",
    email: "employee@email.com",
    team: "",
    location: "LA Branch",
    department: "Marketing",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    imageUrl: "https://randomuser.me/api/portraits/men/10.jpg",
  },
  {
    id: 16,
    parentId: "5",
    givenName: "Scott",
    positionName: "HR assistant",
    phone: "99887766",
    email: "employee@email.com",
    team: "",
    location: "LA Branch",
    department: "Marketing",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    imageUrl: "https://randomuser.me/api/portraits/men/10.jpg",
  },

  {
    id: 18,
    parentId: "3",
    givenName: "James",
    positionName: "Marketer",
    phone: "99887766",
    email: "employee@email.com",
    team: "",
    location: "LA Branch",
    department: "",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    imageUrl: "https://randomuser.me/api/portraits/men/7.jpg",
  },
  {
    id: 19,
    parentId: "3",
    givenName: "Tony",
    positionName: "HR assistant",
    phone: "99887766",
    email: "employee@email.com",
    team: "",
    location: "LA Branch",
    department: "Marketing",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    imageUrl: "https://randomuser.me/api/portraits/men/8.jpg",
  },
  {
    id: 20,
    parentId: "3",
    givenName: "Sally",
    positionName: "HR assistant",
    phone: "99887766",
    email: "employee@email.com",
    team: "",
    location: "LA Branch",
    department: "Marketing",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    imageUrl: "https://randomuser.me/api/portraits/women/9.jpg",
  },
  {
    id: 21,
    parentId: "3",
    givenName: "Scott",
    positionName: "Teacher",
    phone: "99887766",
    email: "employee@email.com",
    team: "",
    location: "LA Branch",
    department: "Marketing",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    imageUrl: "https://randomuser.me/api/portraits/men/10.jpg",
  },

  {
    id: 22,
    parentId: "6",
    givenName: "James",
    positionName: "Teacher",
    phone: "99887766",
    email: "employee@email.com",
    team: "",
    location: "LA Branch",
    department: "Marketing",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    imageUrl: "https://randomuser.me/api/portraits/men/1.jpg",
  },
  {
    id: 23,
    parentId: "6",
    givenName: "Tony",
    positionName: "Developer",
    phone: "99887766",
    email: "employee@email.com",
    team: "",
    location: "LA Branch",
    department: "Marketing",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    imageUrl: "https://randomuser.me/api/portraits/men/8.jpg",
  },
  // {
  //   id: 17,
  //   parentId: "7",
  //   givenName: "Sally",
  //   positionName: "Developer",
  //   phone: "99887766",
  //   email: "employee@email.com",
  //   team: "",
  //   location: "LA Branch",
  //   department: "Marketing",
  //   description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  //   imageUrl: "https://randomuser.me/api/portraits/women/9.jpg",
  // },
  // {
  //   id: 18,
  //   parentId: "8",
  //   givenName: "Scott",
  //   positionName: "Teacher",
  //   phone: "99887766",
  //   email: "employee@email.com",
  //   team: "",
  //   location: "LA Branch",
  //   department: "Marketing",
  //   description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  //   imageUrl: "https://randomuser.me/api/portraits/men/10.jpg",
  // },
  // {
  //   id: 19,
  //   parentId: "7",
  //   givenName: "Tony",
  //   positionName: "Developer",
  //   phone: "99887766",
  //   email: "employee@email.com",
  //   team: "",
  //   location: "LA Branch",
  //   department: "Marketing",
  //   description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  //   imageUrl: "https://randomuser.me/api/portraits/men/8.jpg",
  // },
  // {
  //   id: 20,
  //   parentId: "7",
  //   givenName: "Tony",
  //   positionName: "Developer",
  //   phone: "99887766",
  //   email: "employee@email.com",
  //   team: "",
  //   location: "LA Branch",
  //   department: "Marketing",
  //   description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  //   imageUrl: "https://randomuser.me/api/portraits/men/8.jpg",
  // },
  // {
  //   id: 21,
  //   parentId: "7",
  //   givenName: "Tony",
  //   positionName: "Developer",
  //   phone: "99887766",
  //   email: "employee@email.com",
  //   team: "",
  //   location: "LA Branch",
  //   department: "Marketing",
  //   description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  //   imageUrl: "https://randomuser.me/api/portraits/men/8.jpg",
  // },
  // {
  //   id: 22,
  //   parentId: "7",
  //   givenName: "Tony",
  //   positionName: "Developer",
  //   phone: "99887766",
  //   email: "employee@email.com",
  //   team: "",
  //   location: "LA Branch",
  //   department: "Marketing",
  //   description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  //   imageUrl: "https://randomuser.me/api/portraits/men/8.jpg",
  // },
  // {
  //   id: 23,
  //   parentId: "7",
  //   givenName: "Tony",
  //   positionName: "Developer",
  //   phone: "99887766",
  //   email: "employee@email.com",
  //   team: "",
  //   location: "LA Branch",
  //   department: "Marketing",
  //   description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  //   imageUrl: "https://randomuser.me/api/portraits/men/8.jpg",
  // },
  // {
  //   id: 24,
  //   parentId: "7",
  //   givenName: "Tony",
  //   positionName: "Developer",
  //   phone: "99887766",
  //   email: "employee@email.com",
  //   team: "",
  //   location: "LA Branch",
  //   department: "Marketing",
  //   description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  //   imageUrl: "https://randomuser.me/api/portraits/men/8.jpg",
  // },
  // {
  //   id: 25,
  //   parentId: "7",
  //   givenName: "Tony",
  //   positionName: "Developer",
  //   phone: "99887766",
  //   email: "employee@email.com",
  //   team: "",
  //   location: "LA Branch",
  //   department: "Marketing",
  //   description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  //   imageUrl: "https://randomuser.me/api/portraits/men/8.jpg",
  // },
  // {
  //   id: 26,
  //   parentId: "7",
  //   givenName: "Tony",
  //   positionName: "Developer",
  //   phone: "99887766",
  //   email: "employee@email.com",
  //   team: "",
  //   location: "LA Branch",
  //   department: "Marketing",
  //   description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  //   imageUrl: "https://randomuser.me/api/portraits/men/8.jpg",
  // },
  // {
  //   id: 27,
  //   parentId: "7",
  //   givenName: "Tony",
  //   positionName: "Developer",
  //   phone: "99887766",
  //   email: "employee@email.com",
  //   team: "",
  //   location: "LA Branch",
  //   department: "Marketing",
  //   description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  //   imageUrl: "https://randomuser.me/api/portraits/men/8.jpg",
  // },
];

export default employees;
