name: API pull request

"on":
  pull_request:
    paths:
      - "backend/**"
env:
  CI: true
  MONGODB_URL: "mongodb://localhost:27017/test"

defaults:
  run:
    working-directory: "./backend"

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: "4.4"

      - name: Node Dependency Install
        run: yarn install

      - name: Run Integration Test
        run: yarn test

      - name: Run Coverage Test
        run: yarn

      - name: Install Ansible dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible==6.1.0

      - name: run exporters playbook
        env:
          SSH_KEY: ${{ secrets.STAGING_KEY }}
        run: |
          cd ..
          echo "$SSH_KEY" > priv.key
          chmod 600 priv.key
          cat priv.key
          export ANSIBLE_HOST_KEY_CHECKING=False
          ansible-galaxy install stephdewit.nvm
          ansible-playbook --private-key=priv.key -i hosts/staging --diff preview.yml -u root

      # - name: Run playbook
      #   uses: dawidd6/action-ansible-playbook@v2

      #   with:
      #     # Required, playbook filepath
      #     playbook: preview.yml
      #     # Optional, SSH private key
      #     key: ${{secrets.SSH_PRIVATE_KEY}}
      #     # Optional, literal inventory file contents
      #     options: |
      #       --inventory hosts/staging
      #       --verbose
