name: Nest-hr deployment when merge
"on":
  pull_request:
    types: [closed]
    paths:
      - "frontend/**"

defaults:
  run:
    working-directory: "./frontend"

jobs:
  Deployment:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "yarn"
          cache-dependency-path: "**/yarn.lock"

      - name: Project setup
        run: |
          cd frontend
          yarn && yarn add --global vercel@latest
      - name: Production deploy
        uses: amondnet/vercel-action@v19
        with:
          vercel-token: ${{ secrets.VERCEL_PERSONAL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./frontend
